[package]
name = "abi-to-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = "0.6.2"
reqwest = "0.11.9"
tokio = { version = "1", features = ["full"] }
clap = "3.0.14"
